### ISSUE TITLE
Pick-up function does not work

### ISSUE THREAD

**Issue by deathrattle666** [crdroidandroid/android_device_xiaomi_whyred#1]
"Pick-up function" in ambient mode does not work as expected.
While activated in crDroid settings, it turns display on and off permanently without any picking up.

I am on beginner level concerning android devices.
Please instruct me, if there is more I can do to help fixing the issue.

**Comment by root2raj** [comment]
Hey! The issue has been fixed in today's build. Please check it out and report if any issues found.

**Comment by deathrattle666** [comment]
Thanks a lot! It works now! :-)
