### ISSUE TITLE
adb device responses with "unauthorized"

### ISSUE THREAD

**Issue by deathrattle666** [crdroidandroid/android_device_xiaomi_whyred#2]
The crdroid rom v6.7 is using unrestricted ADBD which is tied to certain system props. Disable magiskhide and reboot will fix the issue.  While v6.6. is working as expected. v6.7 does not...

Is it possible to get this solved within one of the upcoming rom versions? Thx!

**Comment by gwolf2u** [comment]
Is solved on source level already

**Comment by deathrattle666** [comment]
Great. Thank you very much!
