### ISSUE TITLE
[Bug] Wake from power off state broken

### ISSUE THREAD

**Issue by 1alessandro1** [crdroidandroid/android_device_xiaomi_whyred#3]
Hi, yesterday I've installed crDroid 7.5 flashing it over a previous installation of crDroid7.4, which was installed with a clean flash at the time. Everything was working perfectly with that build, even 5GHz WiFi, Wake from the power off state (for alarms) was perfect.

However with the commits from 20 Mar to master version for branch 11.0, wake from the power off state is now broken and I cannot rely on my phone anymore to use it as an alarm (even when I turn it off in the evening) 

What logs can I provide to debug the issue? 

The steps to reproduce this are: flash crDroid 7.5, set up an alarm at +20 minutes from the current time, turn off the device and see if it wakes up in time to actually play that alarm.

Please report if I'm the only one to experience this, in order for me to understand if this is only a peculiar issue on my side or a global issue introduced with crDroid 7.5

Thank you for your patience

**Comment by gwolf2u** [comment]
closed due to inactivity

**Comment by 1alessandro1** [comment]
@gwolf2u the issue persists. I asked for:

> What logs can I provide to debug the issue?

**Comment by Venerapanski** [comment]
thank you, I have already solved this problem.  all the best to you, take care of yourself.!
--
Отправлено из myMail для Android среда, 12 мая 2021г., 23:16 +03:00 от 1alessandro1  ***@***.*** :

***@***.*** the issue persists. I asked for:

**Comment by dreamwhite** [comment]
> thank you, I have already solved this problem.  all the best to you, take care of yourself.!

Ehm, can you gently tell us the procedure to fix this problem? I'm really interested in the possible solution...
